-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 16:04:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema newledgerapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newledgerapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newledgerapi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `newledgerapi` ;

-- -----------------------------------------------------
-- Table `newledgerapi`.`entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newledgerapi`.`entries` ;

CREATE TABLE IF NOT EXISTS `newledgerapi`.`entries` (
  `entry_id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `description` TEXT NOT NULL,
  `vendor` VARCHAR(255) NOT NULL,
  `amount` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`entry_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `newledgerapi`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newledgerapi`.`users` ;

CREATE TABLE IF NOT EXISTS `newledgerapi`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `newledgerapi`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newledgerapi`.`profiles` ;

CREATE TABLE IF NOT EXISTS `newledgerapi`.`profiles` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `zip` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `profiles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `newledgerapi`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- UNCOMMENT THIS IF YOU WANT FILLER DATA
-- -----------------------------------------------------

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Office furniture', 'IKEA', 2199.99);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Server maintenance', 'Dell', 5670.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Employee training', 'Udemy', 999.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Travel expenses', 'American Airlines', 1234.56);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Advertising', 'Google Ads', 3500.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Legal consultation', 'Smith & Associates', 2000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Office rent', 'City Center Real Estate', 5000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Utilities', 'PowerCo', 789.45);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Company vehicles', 'Toyota', 45000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Catering for event', 'Tasty Bites', 1500.75);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('IT equipment', 'Best Buy', 3789.50);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Insurance premium', 'SafeGuard Insurance', 2500.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Employee benefits', 'HealthPlus', 10000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Office cleaning', 'CleanPro Services', 450.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Software development tools', 'JetBrains', 799.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Conference tickets', 'TechCon 2024', 2999.99);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Printer ink', 'Office Depot', 345.67);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Team building event', 'Adventure Zone', 1200.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Shipping costs', 'FedEx', 567.89);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Website redesign', 'WebWizards Inc', 7500.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Customer refund', 'John Doe', 99.99);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Cybersecurity audit', 'SecureNet Solutions', 4000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Holiday party expenses', 'Party Planet', 3000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Subscription service', 'Adobe Creative Cloud', 599.88);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Office plants', 'Green Thumb Nursery', 250.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Parking fees', 'City Parking Authority', 200.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Professional membership', 'Industry Association', 350.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Employee awards', 'Trophy World', 500.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Charitable donation', 'Local Food Bank', 1000.00);

-- INSERT INTO `newledgerapi`.`entries` (`description`, `vendor`, `amount`)
-- VALUES ('Recruitment agency fees', 'TalentHunters', 5000.00);